### ISSUE TITLE
viewlyrics seems out of service

### ISSUE THREAD

**Issue by lakedai** [osdlyrics/osdlyrics#100]

**Comment by PedroHLC** [comment]
ViewLyrics-based code was already dropped in https://github.com/osdlyrics/osdlyrics/pull/89

A lot of distributions haven't published the new releases/updates yet, please request to your distribution that they bump the version to [0.5.9](https://github.com/osdlyrics/osdlyrics/releases/tag/0.5.9)

**Comment by PedroHLC** [comment]
Note that two other lyrics provided were also added meanwhile, thanks to [dasj19](github.com/dasj19). That may help you with the ViewLyrics absence.
