### ISSUE TITLE
wrong artist from telegram-desktop

### ISSUE THREAD

**Issue by poly000** [osdlyrics/osdlyrics#106]
`M, i, t, c, h, i, e, , M, ，, 初, 音, ミ, ク` shows in Osdlyrics,

But in telegram, it's 
![image](https://user-images.githubusercontent.com/34085039/131289118-8e53dc01-5b09-4e9e-a262-ab48a48f50f6.png)

**Comment by PedroHLC** [comment]
This is probably a duplicate of #99
