### ISSUE TITLE
Move issues from PedroHLC/osdlyrics to here

### ISSUE THREAD

**Issue by pradyunsg** [osdlyrics/osdlyrics#11]
Move issues from PedroHLC/osdlyrics to here because it'll make it easier to know where to report issues.

Maybe even 
- add a message to the PedroHLC repository that issues should be reported here 
- disable issues on that repository

**Comment by PedroHLC** [comment]
I requested the only useful issue I have found to be moved to here. There were also two interesting issues from @lenoch (font symbol error, translation update). Hope he doesn't mind recreating them 😆 .
Issues should now stay here!
