### ISSUE TITLE
build varies from date again

### ISSUE THREAD

**Issue by bmwiedemann** [osdlyrics/osdlyrics#110]
The build of `osdlyrics` in openSUSE had been reproducible since #34 but that changed with 
https://github.com/osdlyrics/osdlyrics/pull/96/commits/b9628612d11d2da79d6416d153a374ffdb774cf1

One simple fix would be to add `-r README.md` now. Or redesign how that fallback works. See the discussion in #34 on possible approaches.

**Comment by PedroHLC** [comment]
Maybe we could change `OL_BUILD_VER` to 0 unless defined by the user? Or just start using `git describe --always --tags --dirty=+` in `OL_VERSION` with no intermediaries (and a single hardcoded fallback).

**Comment by PedroHLC** [comment]
I'm working in a change in https://github.com/osdlyrics/osdlyrics/tree/configure-version-git where having a `.git` directory + `git` in PATH, will lead to `git describe` being used, otherwise, the hard-coded version.
