### ISSUE TITLE
Python pycurl and future on Arch Linux

### ISSUE THREAD

**Issue by Denzy7** [osdlyrics/osdlyrics#112]
Add the following pacman dependencies to PKGBUILD
`python-pycurl python-future`

**Comment by PedroHLC** [comment]
Please contact [Felix Yan](https://archlinux.org/packages/?maintainer=felixonmars) about it. We only maintain the [AUR's PKGBUILD](https://github.com/osdlyrics/pkgbuild-osdlyrics-git).

**Comment by Denzy7** [comment]
Looks like [its been already reported](https://bugs.archlinux.org/task/74435?project=5&string=osdlyrics). But the package has not been updated in about 4 months!
