### ISSUE TITLE
Lyrics not synced after manually selecting song in deadbeef

### ISSUE THREAD

**Issue by himekifee** [osdlyrics/osdlyrics#113]
I tried my best to debug but I have absolutely no clue what is going wrong. After picking a song manually from the `deadbeef` playlist, `osdlyrics` just stuck at position 0. I inspected `dbus`, call `org.mpris.MediaPlayer2.player.Position` from `org.mpris.MediaPlayer2.DeaDBeeF` service got correct position. Call  `org.mpris.MediaPlayer2.player.Position` from `org.osdlyrics.PlayerProxy.Mpris2` or `org.mpris.MediaPlayer2.osdlyrics` got 0. However, `clementine` works properly. I'm out of trick to figure out what's happening there. If anybody gets luck please tell me how to solve this. Too frustrating.

**Comment by kbsky** [comment]
I cannot reproduce this. Arch Linux, latest OSD Lyrics, DeaDBeeF 1.9.1. Do you have something that is 100% reproducible? Also make sure to use the latest OSD Lyrics release.

**Comment by himekifee** [comment]
I reproduce 100% of the time on my machine... Use latest `osdlyrics-git 0.5.11.r4.g23d9f56-1` and `aur/deadbeef 1.9.1-1`. So you double-click on a song, and lyrics change and scroll with timestamp?

**Comment by kbsky** [comment]
Yep, all good, strange... I have basically an empty config as I never use DeaDBeeF otherwise. Try a clean config and an empty playlist and see if it still happens.

**Comment by himekifee** [comment]
I still can reproduce it 100 percently after deleting `~/.config/deadbeef` and `~/.config/osdlyrics` which makes me think if there is a deeper environment issue.

**Comment by himekifee** [comment]
I cannot reproduce it on another machine. Will investigate further.

**Comment by himekifee** [comment]
I used `deadbeef-git`, and it does not happen anymore for now.

**Comment by kbsky** [comment]
Well that is interesting... Forgot to ask, what's your version of the MPRIS2 plugin?

**Comment by himekifee** [comment]
`aur/deadbeef-mpris2-plugin 1.14-1`. Well, not happening since switched to `git`. Closing the issue.
