### ISSUE TITLE
How to move the dock view

### ISSUE THREAD

**Issue by akash-258** [osdlyrics/osdlyrics#115]
The dock was originally placed at top left, somehow went in the middle, now I cannot move it anywhere. Is there a way ?
Also can I somehow place scrolling windows above all apps, like I can with any normal window ?

**Comment by PedroHLC** [comment]
There is the scrolling and the OSD mode, the first behaves as a window, the second as a floating OSD over all windows. If you locked the position, you can unlock it on the tray icon.

**Comment by akash-258** [comment]
Thanks, moving dock functionality was always there, my bad. Still is there a way to keep scrolling window above other apps, as I prefer that way of viewing lyrics ?

**Comment by PedroHLC** [comment]
> Still is there a way to keep scrolling window above other apps, as I prefer that way of viewing lyrics ?

Indeed, there is none, please, fill a new feature-request issue, with "scrolling OSD"
