### ISSUE TITLE
Request: Update changelog

### ISSUE THREAD

**Issue by iven** [osdlyrics/osdlyrics#12]
Please update changelog file, or the releases page, to let us know what changed these years. Thanks!

**Comment by PedroHLC** [comment]
Ouch, change log is quite old. Last registered commit was 524cfc4a1f5488973d0c26578dbc069852c80e5d, this means we have to add every commit made after...
By now, one may find more interesting to take a look at commits made in #8 and #9, it's specifically what was changed in our gits, but you'll find more bug fixing and required modernizations than new features.

Don't give hopes to changelog, it may be replaced by something automatically generated using git's logs, and for releases only.

**Comment by iven** [comment]
I mean you can write some release notes that summarizes the main features and bugfixes, so users don't have to dig into the commit messages to know what have been changed.

The main changes I can find from the commit logs are:
* Add ViewLyrics as new source
* Fix xiami lyrics fetching

I'm not sure if I missed something.
