### ISSUE TITLE
Bug: Auto search set wrong title / artist facing special character

### ISSUE THREAD

**Issue by zetako** [osdlyrics/osdlyrics#125]
### Detail
When the song's title / artist string contain some special character, OSDLyrics will fail to get correct result. This can happened in a variety of situations, the image below is only an example. In this case, title string contain a `"."` and OSDLyrics just ignore anything before it.
![Screenshot_20220906_095329](https://user-images.githubusercontent.com/54136740/188531774-a87b79c0-7a31-4975-9273-5d2c092df357.png)
### Info
I'm using [Rocket1184/electron-netease-cloud-music](https://github.com/Rocket1184/electron-netease-cloud-music) to play music, and it supporting MPRIS2. The information it send out should be fine, since I can get correct information from my KDE taskbar plugin. My system is manjaro, and I'm using a OSDLyrics from its "community" repo, with version 0.5.11-1 now.
### Others
- I would like to provide more infos, and I will collect all character and the context when this happened, update it later. This issue don't happened frequently, so it takes times.
- I also tried run OSDLyrics in terminal but nothing printed when error occurred, maybe I need some args to make it print more information?

**Comment by kbsky** [comment]
Thanks for this report, I have noticed that too on some other symbol (possibly comma). I don't think it has much to do with the player. I'll try to investigate.
