### ISSUE TITLE
Brainstorm: Communication channels

### ISSUE THREAD

**Issue by Corax26** [osdlyrics/osdlyrics#13]
This new development has got me a bit excited, thanks @tigersoldier again for making this possible :-)

So I think that it would be good to have more ways to communicate between OSD Lyrics developers and maintainers. Issues and PRs are fine for specific topics and patches, and they mostly remove the need for a mailing list, but sometimes we may just want to have an informal discussion about any topic. How about using IRC? We could create an official #osdlyrics channel on freenode (I think it's the most appropriate place), that anyone could join.

@PedroHLC and @lenoch, do you think having an IRC channel would be useful? Right now I think it'd be good for the three of us (and anyone interested in OSD Lyrics' development) to have a chat about short terms plans (next release, etc.), and I feel that issues are not the best place to do that.

**Comment by PedroHLC** [comment]
What about a supergroup on Telegram, or Gitter (seems to be trending on GitHub)??

**Comment by lenoch** [comment]
Gitter looks good to me, for a start. I would prefer an independent service I could integrate in Pidgin. I used to be very fond of XMPP/Jabber but I don't remember even trying chatrooms (MUC). I can see an (unofficial?) Telegram plugin for Pidgin so I guess the issue is solved for me, all three options are feasible for me.

**Comment by lenoch** [comment]
Or, an IRC channel would do good but we should like to have a bot to take care of logging. I think I could run one on my home server, if necessary (I assume there is an easy way to do this).

**Comment by PedroHLC** [comment]
As an experiment:
https://gitter.im/OSDLyrics/Lobby

**Comment by PedroHLC** [comment]
As gitter did not became glamorous and is falling into the shadows, do you guys would like a new room for dev and suport talking? In these days I'm mostyle active in Telegram and Discord...

**Comment by Corax26** [comment]
Sure, why not. I'm using both Discord and Telegram, no particular preference.

**Comment by PedroHLC** [comment]
So let's go to Discord:
https://discord.gg/anUy3K

**Comment by SolarAquarion** [comment]
the discord link timed out

**Comment by PedroHLC** [comment]
There isn't anyone there besides me, but here it's: https://discord.gg/cbhZq9Z

**Comment by himekifee** [comment]
Unfortunately the discord link has expired, could you please renew that link, thanks.

**Comment by PedroHLC** [comment]
Sure: https://discord.gg/vHC2Q3YUuA
But do notice, there is nobody there but me, kind of an empty place :sweat_smile:

**Comment by akash-258** [comment]
Update the discord link in readme plz

**Comment by kbsky** [comment]
Actually updating in the README that is ;) Here you go: #120
