### ISSUE TITLE
How to compile this on Xubuntu Zesty?

### ISSUE THREAD

**Issue by AryToNeX** [osdlyrics/osdlyrics#21]
Running autogen.sh fails with error code 1
so idk which dependencies are needed

**Comment by Corax26** [comment]
What does autogen.sh say? Not sure on Ubuntu but you can find the dependencies for Arch Linux [here](https://aur.archlinux.org/packages/osdlyrics-git/) (there should be similar packages on Ubuntu).

**Comment by GLolol** [comment]
For Debian or Ubuntu, you probably need to install the packages listed here: https://github.com/utopia-repository/osdlyrics/blob/master/debian/control#L5-L13

**Comment by PedroHLC** [comment]
Note here: if PR #24 from @cweiske get pushed, I close this one.
