### ISSUE TITLE
configure links to code.google.com

### ISSUE THREAD

**Issue by cweiske** [osdlyrics/osdlyrics#22]
At the end of `./configure`'s output the following is written:

> Report bugs to <http://code.google.com/p/osd-lyrics/issues/list>.

This should probably be changed to https://github.com/osdlyrics/osdlyrics/issues

**Comment by Corax26** [comment]
Sorry it took me so long to reply...

Yes you're right, in fact there are 30 hits for 'code.google.com' in the code base (due to the About dialogue and the translations). I'll create a PR to make them point to here instead, thanks for the report!
