### ISSUE TITLE
org.osdlyrics.Daemon exited with status 1 / pycurl missing

### ISSUE THREAD

**Issue by cweiske** [osdlyrics/osdlyrics#23]
I successfully installed osdlyrics from git on Ubuntu 16.04 and got an error starting it:

```
$ osdlyrics
*Error*: in function _start_daemon_cb: ol_main.c[758]
Unable to start daemon: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.osdlyrics.Daemon exited with status 1
```

When starting the daemon manually, a useful error message was reported:
```
$ osdlyrics-daemon --help
Traceback (most recent call last):
  File "/usr/local/lib/osdlyrics/daemon/main.py", line 29, in <module>
    from osdlyrics.metadata import Metadata
  File "/usr/local/lib/python2.7/dist-packages/osdlyrics/metadata.py", line 26, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/dist-packages/osdlyrics/utils.py", line 29, in <module>
    import pycurl
ImportError: No module named pycurl
```

It turned out that pycurl was already installed for python3, but not for python2.

The solution was for me:
```
$ sudo pip2 install pycurl
```

Maybe the README should tell about the `pycurl` dependency, or configure should check it.

**Comment by Corax26** [comment]
Looks related to #21, that should be added to the README. The most comprehensive list of dependencies is probably the one in the AUR (since it's actually enforced), we should import the list into the README: https://aur.archlinux.org/packages/osdlyrics-git/
