### ISSUE TITLE
The newest git version can not work with netease-cloud-music

### ISSUE THREAD

**Issue by hillwoodroc** [osdlyrics/osdlyrics#33]
The stable version 0.4.3 can work fine with netease-cloud-music. But the git version can't.

This is the debug information：

pc@pc-07:~/obs work/home:hillwood:branches:multimedia:apps> osdlyrics --debug
*Debug*: in function _client_name_acquired_cb: ol_main.c[632]
Client bus name acquired
*Debug*: in function _name_vanished_cb: ol_main.c[717]
Daemon lost, try to activate it
*Debug*: in function _name_vanished_cb: ol_main.c[730]
Daemon appeared
*Debug*: in function _name_appeared_cb: ol_main.c[652]
Daemon appeared
*Debug*: in function _ping_daemon: ol_main.c[661]
Starting to ping the daemon
*Debug*: in function ol_osd_window_set_bg: ol_osd_window.c[1957]
bg: 0x16f04c0
*Debug*: in function ol_image_button_size_request: ol_image_button.c[67]
request: 22 x 22
*Debug*: in function ol_image_button_size_request: ol_image_button.c[67]
request: 22 x 22
*Debug*: in function ol_image_button_size_request: ol_image_button.c[67]
request: 22 x 22
*Debug*: in function ol_image_button_size_request: ol_image_button.c[67]
request: 22 x 22
*Debug*: in function ol_image_button_size_request: ol_image_button.c[67]
request: 22 x 22
*Debug*: in function ol_osd_window_update_child_allocation: ol_osd_window.c[940]
set child allocation
*Debug*: in function ol_image_button_size_allocate: ol_image_button.c[77]
allocation: (457, 55) 22 x 22
*Debug*: in function ol_image_button_size_allocate: ol_image_button.c[77]
allocation: (479, 55) 22 x 22
*Debug*: in function ol_image_button_size_allocate: ol_image_button.c[77]
allocation: (501, 55) 22 x 22
*Debug*: in function ol_image_button_size_allocate: ol_image_button.c[77]
allocation: (523, 55) 22 x 22
*Debug*: in function ol_image_button_size_allocate: ol_image_button.c[77]
allocation: (545, 55) 22 x 22
*Debug*: in function ol_osd_window_set_line_alignment: ol_osd_window.c[1343]
ol_osd_window_set_line_alignment:0-0.000000
*Debug*: in function ol_osd_window_set_line_alignment: ol_osd_window.c[1343]
ol_osd_window_set_line_alignment:1-1.000000
*Debug*: in function _active_color_changed_cb: ol_osd_module.c[360]
len = 3
*Debug*: in function _inactive_color_changed_cb: ol_osd_module.c[378]
len = 3
*Debug*: in function ol_osd_window_set_lyric: ol_osd_window.c[1314]
  lyric:(null)
*Debug*: in function ol_osd_window_set_lyric: ol_osd_window.c[1314]
  lyric:(null)
*Debug*: in function ol_osd_window_set_lyric: ol_osd_window.c[1314]
  lyric:(null)
*Debug*: in function ol_osd_window_set_lyric: ol_osd_window.c[1314]
  lyric:(null)
*Debug*: in function ol_osd_window_set_lyric: ol_osd_window.c[1314]
  lyric:(null)
*Debug*: in function ol_image_button_size_request: ol_image_button.c[67]
request: 16 x 16
*Debug*: in function ol_image_button_size_allocate: ol_image_button.c[77]
allocation: (474, 10) 16 x 16
*Debug*: in function _player_lost_cb: ol_main.c[445]
Running netease-cloud-music %U
*Debug*: in function ol_osd_window_set_lyric: ol_osd_window.c[1314]
  lyric:(null)
*Debug*: in function ol_osd_window_set_lyric: ol_osd_window.c[1314]
  lyric:(null)
netease-cloud-music: /lib64/libdbus-1.so.3: no version information available (required by /usr/bin/../lib/netease-cloud-music/lib/libcef.so)
*Debug*: in function ol_osd_window_set_lyric: ol_osd_window.c[1314]
  lyric:(null)
*Debug*: in function ol_osd_window_set_lyric: ol_osd_window.c[1314]
  lyric:(null)
*Debug*: in function _ping_daemon_cb: ol_main.c[701]
Succeed to ping the daemon
*Debug*: in function ol_osd_window_set_lyric: ol_osd_window.c[1314]
  lyric:(null)
*Debug*: in function ol_osd_window_set_lyric: ol_osd_window.c[1314]
  lyric:(null)
*Debug*: in function ol_osd_window_set_lyric: ol_osd_window.c[1314]
  lyric:(null)
*Debug*: in function ol_osd_window_set_lyric: ol_osd_window.c[1314]
  lyric:(null)
*Debug*: in function ol_osd_window_set_lyric: ol_osd_window.c[1314]
  lyric:(null)
*Debug*: in function ol_osd_window_set_lyric: ol_osd_window.c[1314]
  lyric:(null)
*Debug*: in function ol_osd_window_set_lyric: ol_osd_window.c[1314]
  lyric:(null)
*Debug*: in function ol_osd_window_update_child_allocation: ol_osd_window.c[940]
set child allocation
*Debug*: in function ol_image_button_size_allocate: ol_image_button.c[77]
allocation: (468, 59) 22 x 22
*Debug*: in function ol_image_button_size_allocate: ol_image_button.c[77]
allocation: (490, 59) 22 x 22
*Debug*: in function ol_image_button_size_allocate: ol_image_button.c[77]
allocation: (512, 59) 22 x 22
*Debug*: in function ol_image_button_size_allocate: ol_image_button.c[77]
allocation: (534, 59) 22 x 22
/usr/bin/netease-cloud-music: /lib64/libdbus-1.so.3: no version information available (required by /usr/bin/../lib/netease-cloud-music/lib/libcef.so)
/proc/self/exe: /lib64/libdbus-1.so.3: no version information available (required by /usr/bin/../lib/netease-cloud-music/lib/libcef.so)
[1128/111659.954432:ERROR:nss_util.cc(802)] After loading Root Certs, loaded==false: NSS error code: -8018
Local file: "" ("netease-cloud-music")

**Comment by Corax26** [comment]
Sorry for the (very) late reply.

Can you elaborate about how it doesn't work? Do you get the versioning error from the dynamic linker even when you run netease-cloud-music manually?

**Comment by PedroHLC** [comment]
No response since 2017, closing it!
