### ISSUE TITLE
ViewLyrics seems to be gone, any future for OSD Lyrics?

### ISSUE THREAD

**Issue by Corax26** [osdlyrics/osdlyrics#39]
viewlyrics.com and related domains (minilyrics.com, crintsoft.com) are down, after about a week of 502. This disheartens me, because if ViewLyrics is gone, then we don't have any usable lyrics source left (lrc123 has always been down since I started using OSD Lyrics, and Xiami is rarely useful), which basically means this is the end of OSD Lyrics (which doesn't even support plain TXT) :(

Are there any other potential sources? Musixmatch is the only relevant result Google found, but obviously the LRC API is for commercial licenses only.

**Comment by PedroHLC** [comment]
ViewLyrics.com seems to be back online!

**Comment by Corax26** [comment]
It is, I was really happy when it came back online!! :D Still, that makes me quite worried about its longer-term future... Maybe it is time to try and crawl its whole database to back it up somewhere else :P

**Comment by naaando** [comment]
Hi folks, I'm developing a lyrics displayer for eOS and had stuck in finding good sources for .lrc files, as I see it's a problem of yours too. I've been thinking about how I can address this issue and two possible solutions came to my mind, one is setup a server and another would be a P2P solution.
I want to use your LyricSource services on my project, so any of these solution will fit all.

I'd found some sources (syair, google search with filetype) which can back us online for a while but is really weird to rely on third parties.

**Comment by Corax26** [comment]
Hi @naaando, happy to see that we're not the last ones working on synchronised lyrics! A P2P solution would be interesting, but the issue is that you need enough users to make it viable, and to be honest I'm not sure we have such a critical mass. Also, it's not necessarily a good idea to use a P2P approach by default (some users may not like it, and companies often ban P2P traffic inside their network).

Interesting that you've found other sources, my Googling wasn't very successful last time! Have you found some API to query Syair?

Also, do feel free to use and adapt our LyricSource services, that's what GPL is for :) The other day I made a quick hack to turn the ViewLyrics one into a standalone downloader, to download multiple lyrics at once. So far ViewLyrics is still there, but who knows for how long...

**Comment by naaando** [comment]
As far as I know Syair doesn't have a public API , so the plugin would need to scrap the .lrc that is plain text inside the site, but I don't know if it's legal at all.

Next weekends I'll be hacking LyricSource to use it on my project, would be nice to see your standalone version if I could.

**Comment by muriloventuroso** [comment]
Very interesting idea of a P2P service, can count on my help! Osdlyrics sources appear to be having many problems, but that Syar is promising.

**Comment by Artemiy87** [comment]
http://viewlyrics.com/ seems to be dead. Maybe is there any opportunity to buy it to make it live? Or what? I have small base of rock songs, who has the same? Have an offer to make exchange with them.

**Comment by PedroHLC** [comment]
> http://viewlyrics.com/ seems to be dead. Maybe is there any opportunity to buy it to make it live? Or what? I have small base of rock songs, who has the same? Have an offer to make an exchange with them.

I find this possibility hard to believe. First, all the content of ViewLyrics used to be copyrighted. Second, we always had to break their encryption every once in a while to keep it working for us, and they kept making it harder in every interaction.
