### ISSUE TITLE
Bug: Downloaded lrc file has a NULL ending which breaks texts editors.

### ISSUE THREAD

**Issue by gumblex** [osdlyrics/osdlyrics#51]
The downloaded lrc files has a NUL ending that prevents many editors/players opening. The source is netease music, but I think it's irrelevant.

**Comment by Corax26** [comment]
I do see NULL endings with most lyrics downloaded from ViewLyrics as well. I also observe that editors picky about UTF8 like gedit or mousepad complain about it. I think it should be doable to strip those trailing NULLs, but I'm not sure it could be doable in the generic code (IOW all the sources would need to be modified).

**Comment by PedroHLC** [comment]
LRC files should be human readable, a binary byte shouldn't be there. If it's not original from the source (which probably isn't, why would someone do it?), maybe from the downloader code is writing a byte more than it should...
Which version is this being reported? 0.5 or older?

**Comment by PedroHLC** [comment]
Was this solved with #53  ??

**Comment by gumblex** [comment]
No. I think the problem is in some C code.
