### ISSUE TITLE
Request: upgrade libcurl

### ISSUE THREAD

**Issue by NetherKing1357** [osdlyrics/osdlyrics#65]
Since libcurl3 is listed as a dependancy, OSDLyrics only runs once curl is uninstalled. Would it be possible to port the code to support libcurl4 so I can continue with curl installed on my machine?

OSDLyrics 0.4.3-1
Ubuntu 18.04.2 LTS
GNOME 3.28.2
amd64

**Comment by pjw91** [comment]
`libcurl` is no longer a dependency after ddd397be (master branch).
