### ISSUE TITLE
osdlyrics start faild in openSUSE Leap

### ISSUE THREAD

**Issue by hillwoodroc** [osdlyrics/osdlyrics#66]
pc@pc-07:~/home:hillwood:branches:multimedia:apps> osdlyrics-daemon 
WARNING:root:Cannot activate proxy org.osdlyrics.PlayerProxy.Http: org.freedesktop.DBus.Error.Spawn.ExecFailed: Failed to execute program org.osdlyrics.PlayerProxy.Http: No such file or directory
WARNING:root:Cannot activate proxy org.osdlyrics.PlayerProxy.Mpd: org.freedesktop.DBus.Error.Spawn.ExecFailed: Failed to execute program org.osdlyrics.PlayerProxy.Mpd: No such file or directory
WARNING:root:Cannot activate proxy org.osdlyrics.PlayerProxy.Mpris1: org.freedesktop.DBus.Error.Spawn.ExecFailed: Failed to execute program org.osdlyrics.PlayerProxy.Mpris1: No such file or directory
WARNING:root:Cannot activate proxy org.osdlyrics.PlayerProxy.Mpris2: org.freedesktop.DBus.Error.Spawn.ExecFailed: Failed to execute program org.osdlyrics.PlayerProxy.Mpris2: No such file or directory
ERROR:root:Cannot activate config service
WARNING:root:Cannot activate lyric source org.osdlyrics.LyricSourcePlugin.xiami: org.freedesktop.DBus.Error.Spawn.ExecFailed: Failed to execute program org.osdlyrics.LyricSourcePlugin.xiami: No such file or directory
WARNING:root:Cannot activate lyric source org.osdlyrics.LyricSourcePlugin.viewlyrics: org.freedesktop.DBus.Error.Spawn.ExecFailed: Failed to execute program org.osdlyrics.LyricSourcePlugin.viewlyrics: No such file or directory
WARNING:root:Cannot activate lyric source org.osdlyrics.LyricSourcePlugin.netease: org.freedesktop.DBus.Error.Spawn.ExecFailed: Failed to execute program org.osdlyrics.LyricSourcePlugin.netease: No such file or directory
WARNING:root:Cannot activate lyric source org.osdlyrics.LyricSourcePlugin.lrc123: org.freedesktop.DBus.Error.Spawn.ExecFailed: Failed to execute program org.osdlyrics.LyricSourcePlugin.lrc123: No such file or directory
ERROR:dbus.proxies:Introspect error on org.osdlyrics.Config:/org/osdlyrics/Config: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: Failed to execute program org.osdlyrics.Config: No such file or directory
ERROR:dbus.proxies:Introspect error on org.osdlyrics.Config:/org/osdlyrics/Config: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: Failed to execute program org.osdlyrics.Config: No such file or directory

**Comment by hillwoodroc** [comment]
pc@pc-07:~/home:hillwood:branches:multimedia:apps> osdlyrics
Gtk-Message: Failed to load module "unity-gtk-module"
*Error*: in function _start_daemon_cb: ol_main.c[768]
Unable to start daemon: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ExecFailed: Failed to execute program org.osdlyrics.Daemon: No such file or directory

**Comment by windilt** [comment]
similar problem, install dbus, dbus-1-glib, libdbus, python2-dbus-python, python2-pydbus can't solve it.

osdlyrics
*Error*: in function _start_daemon_cb: ol_main.c[758]
Unable to start daemon: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.osdlyrics.Daemon exited with status 1

**Comment by Zzombiee2361** [comment]
I managed to get it running by installing these packages:
`python-future python-gi python-dbus python-chardet python-pycurl`

This should be put on the README or wiki. Please note that I'm running Ubuntu LTS 18.04. If for some reason it still throwing the same error, running `osdlyrics-daemon` would give you more helpful error

**Comment by windilt** [comment]
on opensuse or through pip I can't find python-gi , but I installed python-future  python-dbus python-chardet python-pycurl, it still report same error. Maybe python-gi is the key point, but I can't find it...

*Error*: in function _start_daemon_cb: ol_main.c[758]
Unable to start daemon: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.osdlyrics.Daemon exited with status 1

**Comment by windilt** [comment]
I just fix it by install python2-gobject2.

You can find Dependencies in AUR web site.
https://aur.archlinux.org/packages/osdlyrics-git/


    dbus-glib
    desktop-file-utils (desktop-file-utils-git)
    gtk2 (gtk2-patched-gdkwin-nullcheck, gtk2-ubuntu, gtk2-patched-filechooser-icon-view, gtk2-git)
    hicolor-icon-theme (hicolor-icon-theme-git)
    libnotify (libnotify-gtk2, libnotify-id-git, libnotify-id)
    python2-chardet
    python2-dbus
    python2-gobject2
    python2-pycurl
    sqlite (sqlite-fossil, sqlite-replication)
    intltool (make)
    gobject-introspection-runtime (gobject-introspection-git) (optional) – proxy detection in Gnome
    kdebindings-python2 (optional) – proxy detection in KDE
    python2-mpd (optional) – to interface with MPD

**Comment by PedroHLC** [comment]
In ArchLinux, with the current master branch, this seems enough to build in a clean chroot an install on a new setup:
```
depends=(dbus-glib desktop-file-utils gtk2 hicolor-icon-theme libnotify
         python-{future,dbus,chardet,gobject,pycurl}
         sqlite)
makedepends=(intltool)
```
(NOTE: python3 executable set in PYTHON envvar)

Hi @hillwoodroc , if it still doesn't work feel free to reopen this issue!
