### ISSUE TITLE
Error when run ./autogen.sh

### ISSUE THREAD

**Issue by shootheart** [osdlyrics/osdlyrics#67]
What does this mean?
```
config.status: error: po/Makefile.in.in was not created by intltoolize.
```

**Comment by PedroHLC** [comment]
Hi @shootheart I must have seen this issue, got distracted and completely forgot about it...

This should be enougth to build:
```
./autogen.sh
./configure --prefix=/usr PYTHON=/usr/bin/python
make
sudo make install
```

If it doesn't work again, feel free to reopen this issue.
