### ISSUE TITLE
[Q] completely disable online search

### ISSUE THREAD

**Issue by eadmaster** [osdlyrics/osdlyrics#83]
I've disabled all the Lyric sites in the "Network" Preferences tab, but everytime a new song starts playing the "choose LRC file to download" dialog still appear.

**Comment by Andras-Adamov** [comment]
Maybe You can use an invalid proxy address in manual proxy mode. It won't connect. :)

**Comment by ichaoX** [comment]
> Maybe You can use an invalid proxy address in manual proxy mode. It won't connect. :)

That may generate an error traceback to the system log. It seems that the `Download/proxy-password` configuration key is inconsistent in some places.

https://github.com/osdlyrics/osdlyrics/blob/f75fa97605a87ced33017ada7e665280fd3400c4/src/ol_option.c#L135-L139
https://github.com/osdlyrics/osdlyrics/blob/f75fa97605a87ced33017ada7e665280fd3400c4/python/utils.py#L131-L138

**Comment by ichaoX** [comment]
This looks like a bug. A disabled download-engine should not be automatically searched and downloaded.

The function `ol_lyric_source_search_default` passes all `source_ids` to `ol_lyric_source_search`, even if the source has not been enabled.

https://github.com/osdlyrics/osdlyrics/blob/f75fa97605a87ced33017ada7e665280fd3400c4/src/ol_lyric_source.c#L533-L559


@PedroHLC , what do you think if I add a check here to confirm if the source is enabled or not?

```c
  for (; sources; sources = g_list_delete_link (sources, sources))
  {
    OlLyricSourceInfo *info = sources->data;
    if (ol_lyric_source_info_get_enabled (info))
    {
      source_ids = g_list_prepend (source_ids,
                                   g_strdup (ol_lyric_source_info_get_id (info)));
    }
    ol_lyric_source_info_free (info);
  }
```

**Comment by PedroHLC** [comment]
> what do you think if I add a check here to confirm if the source is enabled or not?

Looks KISS and good to me. You are welcome to open a PR for us to test it better.
