### ISSUE TITLE
Unable to start osdlyrics - D-Bus Error

### ISSUE THREAD

**Issue by thx4coding** [osdlyrics/osdlyrics#86]
When I try to start osdlyrics, I get the following error message:

> dbus[4272]: arguments to dbus_message_iter_append_basic() were incorrect, assertion "_dbus_check_is_valid_utf8 (*string_p)" failed in file ../../../dbus/dbus-message.c line 2754.
This is normally a bug in some application using the D-Bus library.

>   D-Bus not built with -rdynamic so unable to print a backtrace
Aborted (core dumped)

I checked the dependencies, but it seems that I have erverything needed installed.
Would appreciate any help.

Edit: Same issue as unconfirmed closed bug #48

**Comment by snorez** [comment]
Hi, @thx4coding . Can you try pull request #79?

**Comment by thx4coding** [comment]
Hello @snorez , thanks for the reply.
With that version I get the same output as described in issue #75.

When I run `python3 /usr/lib/osdlyrics/daemon/main.py`, I get the following output:

> Traceback (most recent call last):
  File "/usr/lib/osdlyrics/daemon/main.py", line 27, in <module>
    from osdlyrics import PACKAGE_VERSION
ModuleNotFoundError: No module named 'osdlyrics'

With  `python2 /usr/lib/osdlyrics/daemon/main.py`, I get:

> Traceback (most recent call last):
  File "/usr/lib/osdlyrics/daemon/main.py", line 21, in <module>
    from builtins import super
ImportError: No module named builtins

**Comment by snorez** [comment]
I guess you are using PYTHON2, right? You compiled the source with `./configure --prefix=/usr PYTHON=/usr/bin/python2`. Thus, we don't use python3 to launch osdlyrics.
The output of python2 means that you don't have builtins module. Maybe you should try to install `python-future` package.

**Comment by thx4coding** [comment]
At first I tried using Python3, but after getting the above output and reading issue #78, I removed osdlyrics and recompiled it for python2 with `./configure --prefix=/usr PYTHON=/usr/bin/python2`.

The future package is already installed over pip3.
I also tried to install pip for python2, but even with the universe repository it says "E: Unable to locate package pip".

**Comment by snorez** [comment]
Okay, then you have to use Python3 to compile osdlyrics.

> The future package is already installed over pip3. 

This package you installed is for python3, not for python2.

> ModuleNotFoundError: No module named 'osdlyrics'

For python3, make sure you have `/usr/lib/python3/dist-packages/osdlyrics/`.

**Comment by snorez** [comment]
A little trick, try install from the Ubuntu(If you are using this distro) repos, then compile and copy the executable file `osdlyrics` to `/usr/bin/osdlyrics`. This can resolve the very first one error, which is
> dbus[4272]: arguments to dbus_message_iter_append_basic() were incorrect, assertion "_dbus_check_is_valid_utf8 (*string_p)" failed in file ../../../dbus/dbus-message.c line 2754.

**Comment by thx4coding** [comment]
This little trick worked for me, thank you very much @snorez .

> A little trick, try install from the Ubuntu(If you are using this distro) repos, then compile and copy the executable file osdlyrics to /usr/bin/osdlyrics. This can resolve the very first one error
