### ISSUE TITLE
lyricsources: lrc123 and viewlyrics are based on defunct web services

### ISSUE THREAD

**Issue by dasj19** [osdlyrics/osdlyrics#88]
Hi, I just wanted to report that lrc123 and viewlyrics are based on APIs that no longer exist.
I have disabled them from the settings, but I think there should be some code cleanup that removes them from the codebase.

I can take on the task of code removal if it is ok with the maintainers of this project.

**Comment by PedroHLC** [comment]
Sure, just a minute of silence for our gone friends...

🪦 LRC123 
🪦 ViewLyrics
(2009-2019)

If you need to add a linter for helping in the cleanup, feel free to.

**Comment by dasj19** [comment]
I didn't really know them but RIP LRC123 and ViewLyrics.

So I opened the mentioned PR and compiled the app with the changes I made, now there is only Netease and Xiami as sources.

**Comment by PedroHLC** [comment]
Thanks for the contributions.
It makes me happy to see this project surviving.

> but I guess that is another PR to be done.

Yeah, it's better to keep them split.

I'll schedule to release the #89 tonight.

**Comment by dasj19** [comment]
I don't know about the release procedure... but isn't it better to have a bit more features/bugfixes per release?

**Comment by dasj19** [comment]
> It makes me happy to see this project surviving.

Just stumbled upon this project from a 10-year ubuntuanswers page, and I struggled a bit to package it for NixOS (I need to do some cleanup to the packaging script before submitting to NixOS, here are the barebones of the script: https://discourse.nixos.org/t/help-building-a-python-package-that-uses-dbus/13088 ).
I'll try to do the little I can to this project as it brings value to my (huge) song collection.

**Comment by PedroHLC** [comment]
> I don't know about the release procedure... but isn't it better to have a bit more features/bug fixes per release?

We should hide the users from incomplete/untested features but not from general bug fixes. Everybody deserves to have access to them. That's what "minor bumps" are meant for.
~(There were some bug fixes from 2019s that were waiting for more fixes for having a release, and that was totally my mistake)~

>  to package it for NixOS

When you have it ready, feel free to add/link it to the README.md
