### ISSUE TITLE
feature: add new lyricsources

### ISSUE THREAD

**Issue by dasj19** [osdlyrics/osdlyrics#90]
I have looked at xiami's implementation and the current code in the osdlyrics repo references an old version of xiami's website which no longer works.

So I investigated other packages on Github and they make use of Xiami's new API. The new API requires registration and authentication.

I have also checked Musixmatch, but they do not offer synced lyrics in their free plan, and registration is required as well.

So there are the following problems:
1. We need more synced lyrics sources
2. We might need to support authentication with API keys for some of the sources like Xiami

**Comment by PedroHLC** [comment]
We have discussed that previously here https://github.com/osdlyrics/osdlyrics/issues/69
It was also discussed to add a new "bash-compatible" one: https://github.com/osdlyrics/osdlyrics/issues/82

**Comment by dasj19** [comment]
Okay, my bad I should have checked the log before opening a new discussion. I will continue the discussion here: https://github.com/osdlyrics/osdlyrics/issues/69
